"""add asignado_a to pedidos

Revision ID: 197b4a37879d
Revises: 8582f679d83f
Create Date: 2026-06-19 13:10:08.249293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197b4a37879d'
down_revision: Union[str, None] = '8582f679d83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('asignado_a', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_pedidos_asignado_a'), 'pedidos', ['asignado_a'], unique=False)
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['asignado_a'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_index(op.f('ix_pedidos_asignado_a'), table_name='pedidos')
    op.drop_column('pedidos', 'asignado_a')
    # ### end Alembic commands ###
