"""catalogo: marcas, categorias, productos, variantes, atributos, imagenes, resenas

Revision ID: 2402d3d83bad
Revises: 3c4588897dbc
Create Date: 2026-06-15 22:49:32.442895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2402d3d83bad'
down_revision: Union[str, None] = '3c4588897dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributos',
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atributos_external_id'), 'atributos', ['external_id'], unique=False)
    op.create_index(op.f('ix_atributos_slug'), 'atributos', ['slug'], unique=True)
    op.create_table('categorias',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_external_id'), 'categorias', ['external_id'], unique=False)
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    op.create_table('marcas',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_external_id'), 'marcas', ['external_id'], unique=False)
    op.create_index(op.f('ix_marcas_slug'), 'marcas', ['slug'], unique=True)
    op.create_table('productos',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=500), nullable=True),
    sa.Column('marca_id', sa.Uuid(), nullable=True),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_external_id'), 'productos', ['external_id'], unique=False)
    op.create_index(op.f('ix_productos_marca_id'), 'productos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_productos_slug'), 'productos', ['slug'], unique=True)
    op.create_table('valores_atributo',
    sa.Column('atributo_id', sa.Uuid(), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atributo_id', 'slug', name='uq_valor_atributo_slug')
    )
    op.create_index(op.f('ix_valores_atributo_atributo_id'), 'valores_atributo', ['atributo_id'], unique=False)
    op.create_index(op.f('ix_valores_atributo_external_id'), 'valores_atributo', ['external_id'], unique=False)
    op.create_table('producto_imagenes',
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_imagenes_producto_id'), 'producto_imagenes', ['producto_id'], unique=False)
    op.create_table('resenas',
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_resena_rating'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'usuario_id', name='uq_resena_usuario')
    )
    op.create_index(op.f('ix_resenas_producto_id'), 'resenas', ['producto_id'], unique=False)
    op.create_index(op.f('ix_resenas_usuario_id'), 'resenas', ['usuario_id'], unique=False)
    op.create_table('variantes',
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('codigo_barras', sa.String(length=64), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_comparativo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('peso_gramos', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantes_codigo_barras'), 'variantes', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_variantes_external_id'), 'variantes', ['external_id'], unique=False)
    op.create_index(op.f('ix_variantes_producto_id'), 'variantes', ['producto_id'], unique=False)
    op.create_index(op.f('ix_variantes_sku'), 'variantes', ['sku'], unique=True)
    op.create_table('variante_valores',
    sa.Column('variante_id', sa.Uuid(), nullable=False),
    sa.Column('valor_atributo_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['valor_atributo_id'], ['valores_atributo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variante_id', 'valor_atributo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variante_valores')
    op.drop_index(op.f('ix_variantes_sku'), table_name='variantes')
    op.drop_index(op.f('ix_variantes_producto_id'), table_name='variantes')
    op.drop_index(op.f('ix_variantes_external_id'), table_name='variantes')
    op.drop_index(op.f('ix_variantes_codigo_barras'), table_name='variantes')
    op.drop_table('variantes')
    op.drop_index(op.f('ix_resenas_usuario_id'), table_name='resenas')
    op.drop_index(op.f('ix_resenas_producto_id'), table_name='resenas')
    op.drop_table('resenas')
    op.drop_index(op.f('ix_producto_imagenes_producto_id'), table_name='producto_imagenes')
    op.drop_table('producto_imagenes')
    op.drop_index(op.f('ix_valores_atributo_external_id'), table_name='valores_atributo')
    op.drop_index(op.f('ix_valores_atributo_atributo_id'), table_name='valores_atributo')
    op.drop_table('valores_atributo')
    op.drop_index(op.f('ix_productos_slug'), table_name='productos')
    op.drop_index(op.f('ix_productos_marca_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_external_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_marcas_slug'), table_name='marcas')
    op.drop_index(op.f('ix_marcas_external_id'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_external_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_atributos_slug'), table_name='atributos')
    op.drop_index(op.f('ix_atributos_external_id'), table_name='atributos')
    op.drop_table('atributos')
    # ### end Alembic commands ###
