"""costo de proveedor en variantes

Revision ID: 4ef6260ab383
Revises: d472e56d2919
Create Date: 2026-07-20 12:48:07.828443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef6260ab383'
down_revision: Union[str, None] = 'd472e56d2919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variantes', sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variantes', 'costo')
    # ### end Alembic commands ###
