"""add paquetes and paquete_items tables

Revision ID: 8582f679d83f
Revises: 8e427d106ae5
Create Date: 2026-06-19 12:43:50.030871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8582f679d83f'
down_revision: Union[str, None] = '8e427d106ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paquetes',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=500), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('precio_paquete', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquetes_slug'), 'paquetes', ['slug'], unique=True)
    op.create_table('paquete_items',
    sa.Column('paquete_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('variante_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquete_items_paquete_id'), 'paquete_items', ['paquete_id'], unique=False)
    op.create_index(op.f('ix_paquete_items_producto_id'), 'paquete_items', ['producto_id'], unique=False)
    op.create_index(op.f('ix_paquete_items_variante_id'), 'paquete_items', ['variante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paquete_items_variante_id'), table_name='paquete_items')
    op.drop_index(op.f('ix_paquete_items_producto_id'), table_name='paquete_items')
    op.drop_index(op.f('ix_paquete_items_paquete_id'), table_name='paquete_items')
    op.drop_table('paquete_items')
    op.drop_index(op.f('ix_paquetes_slug'), table_name='paquetes')
    op.drop_table('paquetes')
    # ### end Alembic commands ###
