"""carrito y pedidos (checkout)

Revision ID: 8b12fea8d7c6
Revises: d32f9d70eec7
Create Date: 2026-06-16 07:40:46.127833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b12fea8d7c6'
down_revision: Union[str, None] = 'd32f9d70eec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carritos',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carritos_token'), 'carritos', ['token'], unique=True)
    op.create_index(op.f('ix_carritos_usuario_id'), 'carritos', ['usuario_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('nombre_contacto', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('direccion_calle', sa.String(length=255), nullable=True),
    sa.Column('direccion_ciudad', sa.String(length=120), nullable=True),
    sa.Column('direccion_estado', sa.String(length=120), nullable=True),
    sa.Column('direccion_cp', sa.String(length=10), nullable=True),
    sa.Column('direccion_pais', sa.String(length=2), server_default='MX', nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('requiere_factura', sa.Boolean(), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('regimen_fiscal', sa.String(length=10), nullable=True),
    sa.Column('uso_cfdi', sa.String(length=10), nullable=True),
    sa.Column('cp_fiscal', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('envio', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_external_id'), 'pedidos', ['external_id'], unique=False)
    op.create_index(op.f('ix_pedidos_numero'), 'pedidos', ['numero'], unique=True)
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_table('carrito_items',
    sa.Column('carrito_id', sa.Uuid(), nullable=False),
    sa.Column('variante_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_carrito_item_cantidad'),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrito_id', 'variante_id', name='uq_carrito_variante')
    )
    op.create_index(op.f('ix_carrito_items_carrito_id'), 'carrito_items', ['carrito_id'], unique=False)
    op.create_index(op.f('ix_carrito_items_variante_id'), 'carrito_items', ['variante_id'], unique=False)
    op.create_table('pedido_items',
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('variante_id', sa.Uuid(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_pedido_item_cantidad'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_items_pedido_id'), 'pedido_items', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_items_variante_id'), 'pedido_items', ['variante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_items_variante_id'), table_name='pedido_items')
    op.drop_index(op.f('ix_pedido_items_pedido_id'), table_name='pedido_items')
    op.drop_table('pedido_items')
    op.drop_index(op.f('ix_carrito_items_variante_id'), table_name='carrito_items')
    op.drop_index(op.f('ix_carrito_items_carrito_id'), table_name='carrito_items')
    op.drop_table('carrito_items')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_numero'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_external_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_carritos_usuario_id'), table_name='carritos')
    op.drop_index(op.f('ix_carritos_token'), table_name='carritos')
    op.drop_table('carritos')
    # ### end Alembic commands ###
