"""bitacora de auditoria

Revision ID: 8e427d106ae5
Revises: 8b12fea8d7c6
Create Date: 2026-06-16 08:20:58.263537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e427d106ae5'
down_revision: Union[str, None] = '8b12fea8d7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_rol', sa.String(length=120), nullable=True),
    sa.Column('accion', sa.String(length=64), nullable=False),
    sa.Column('entidad', sa.String(length=64), nullable=True),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cambios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_accion'), 'auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_entidad'), 'auditoria', ['entidad'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidad'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_accion'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
