"""rfc y direccion en usuarios

Revision ID: b7825710b072
Revises: 9695913d040d
Create Date: 2026-07-15 17:45:12.613583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7825710b072'
down_revision: Union[str, None] = '9695913d040d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rfc', sa.String(length=13), nullable=True))
    op.add_column('usuarios', sa.Column('direccion_calle', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('direccion_ciudad', sa.String(length=120), nullable=True))
    op.add_column('usuarios', sa.Column('direccion_estado', sa.String(length=120), nullable=True))
    op.add_column('usuarios', sa.Column('direccion_cp', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_usuarios_rfc'), 'usuarios', ['rfc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_rfc'), table_name='usuarios')
    op.drop_column('usuarios', 'direccion_cp')
    op.drop_column('usuarios', 'direccion_estado')
    op.drop_column('usuarios', 'direccion_ciudad')
    op.drop_column('usuarios', 'direccion_calle')
    op.drop_column('usuarios', 'rfc')
    # ### end Alembic commands ###
