"""inventario ledger: almacenes, lotes, stock_movimientos

Revision ID: d32f9d70eec7
Revises: 2402d3d83bad
Create Date: 2026-06-15 23:24:45.976600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32f9d70eec7'
down_revision: Union[str, None] = '2402d3d83bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_almacenes_codigo'), 'almacenes', ['codigo'], unique=True)
    op.create_index(op.f('ix_almacenes_external_id'), 'almacenes', ['external_id'], unique=False)
    op.create_table('lotes',
    sa.Column('variante_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variante_id', 'codigo', name='uq_lote_variante_codigo')
    )
    op.create_index(op.f('ix_lotes_external_id'), 'lotes', ['external_id'], unique=False)
    op.create_index(op.f('ix_lotes_fecha_caducidad'), 'lotes', ['fecha_caducidad'], unique=False)
    op.create_index(op.f('ix_lotes_variante_id'), 'lotes', ['variante_id'], unique=False)
    op.create_table('stock_movimientos',
    sa.Column('variante_id', sa.Uuid(), nullable=False),
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cantidad <> 0', name='ck_movimiento_cantidad_no_cero'),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movimientos_almacen_id'), 'stock_movimientos', ['almacen_id'], unique=False)
    op.create_index(op.f('ix_stock_movimientos_external_id'), 'stock_movimientos', ['external_id'], unique=False)
    op.create_index(op.f('ix_stock_movimientos_lote_id'), 'stock_movimientos', ['lote_id'], unique=False)
    op.create_index(op.f('ix_stock_movimientos_variante_id'), 'stock_movimientos', ['variante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movimientos_variante_id'), table_name='stock_movimientos')
    op.drop_index(op.f('ix_stock_movimientos_lote_id'), table_name='stock_movimientos')
    op.drop_index(op.f('ix_stock_movimientos_external_id'), table_name='stock_movimientos')
    op.drop_index(op.f('ix_stock_movimientos_almacen_id'), table_name='stock_movimientos')
    op.drop_table('stock_movimientos')
    op.drop_index(op.f('ix_lotes_variante_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_fecha_caducidad'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_external_id'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_almacenes_external_id'), table_name='almacenes')
    op.drop_index(op.f('ix_almacenes_codigo'), table_name='almacenes')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
