"""carrito de paquetes

Revision ID: d472e56d2919
Revises: b7825710b072
Create Date: 2026-07-20 08:18:42.637934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd472e56d2919'
down_revision: Union[str, None] = 'b7825710b072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito_paquetes',
    sa.Column('carrito_id', sa.Uuid(), nullable=False),
    sa.Column('paquete_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_carrito_paquete_cantidad'),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrito_id', 'paquete_id', name='uq_carrito_paquete')
    )
    op.create_index(op.f('ix_carrito_paquetes_carrito_id'), 'carrito_paquetes', ['carrito_id'], unique=False)
    op.create_index(op.f('ix_carrito_paquetes_paquete_id'), 'carrito_paquetes', ['paquete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrito_paquetes_paquete_id'), table_name='carrito_paquetes')
    op.drop_index(op.f('ix_carrito_paquetes_carrito_id'), table_name='carrito_paquetes')
    op.drop_table('carrito_paquetes')
    # ### end Alembic commands ###
